---
- hosts: ubuntunode
  sudo: yes
  tasks:
  - name: update cache
    apt:
      update_cache: yes 
  sudo: yes
  tasks: 
  - name: "install nginx server"
    apt:
      name: nginx
      state: present
      
